// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: btreepb.proto

package com.feeyo.raft.proto;

public final class Btreepb {
  private Btreepb() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code raft.Operation}
   */
  public enum Operation
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Insert = 0;</code>
     */
    Insert(0),
    /**
     * <code>Delete = 1;</code>
     */
    Delete(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>Insert = 0;</code>
     */
    public static final int Insert_VALUE = 0;
    /**
     * <code>Delete = 1;</code>
     */
    public static final int Delete_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Operation valueOf(int value) {
      return forNumber(value);
    }

    public static Operation forNumber(int value) {
      switch (value) {
        case 0: return Insert;
        case 1: return Delete;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Operation>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Operation> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Operation>() {
            public Operation findValueByNumber(int number) {
              return Operation.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.feeyo.raft.proto.Btreepb.getDescriptor().getEnumTypes().get(0);
    }

    private static final Operation[] VALUES = values();

    public static Operation valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Operation(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:raft.Operation)
  }

  public interface ElementOrBuilder extends
      // @@protoc_insertion_point(interface_extends:raft.Element)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string key = 1;</code>
     */
    java.lang.String getKey();
    /**
     * <code>string key = 1;</code>
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <code>bytes value = 2;</code>
     */
    com.google.protobuf.ByteString getValue();

    /**
     * <code>string category = 3;</code>
     */
    java.lang.String getCategory();
    /**
     * <code>string category = 3;</code>
     */
    com.google.protobuf.ByteString
        getCategoryBytes();
  }
  /**
   * Protobuf type {@code raft.Element}
   */
  public  static final class Element extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:raft.Element)
      ElementOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Element.newBuilder() to construct.
    private Element(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Element() {
      key_ = "";
      value_ = com.google.protobuf.ByteString.EMPTY;
      category_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Element(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              key_ = s;
              break;
            }
            case 18: {

              value_ = input.readBytes();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              category_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.feeyo.raft.proto.Btreepb.internal_static_raft_Element_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.feeyo.raft.proto.Btreepb.internal_static_raft_Element_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.feeyo.raft.proto.Btreepb.Element.class, com.feeyo.raft.proto.Btreepb.Element.Builder.class);
    }

    public static final int KEY_FIELD_NUMBER = 1;
    private volatile java.lang.Object key_;
    /**
     * <code>string key = 1;</code>
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        key_ = s;
        return s;
      }
    }
    /**
     * <code>string key = 1;</code>
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString value_;
    /**
     * <code>bytes value = 2;</code>
     */
    public com.google.protobuf.ByteString getValue() {
      return value_;
    }

    public static final int CATEGORY_FIELD_NUMBER = 3;
    private volatile java.lang.Object category_;
    /**
     * <code>string category = 3;</code>
     */
    public java.lang.String getCategory() {
      java.lang.Object ref = category_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        category_ = s;
        return s;
      }
    }
    /**
     * <code>string category = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCategoryBytes() {
      java.lang.Object ref = category_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        category_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getKeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, key_);
      }
      if (!value_.isEmpty()) {
        output.writeBytes(2, value_);
      }
      if (!getCategoryBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, category_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getKeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, key_);
      }
      if (!value_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, value_);
      }
      if (!getCategoryBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, category_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.feeyo.raft.proto.Btreepb.Element)) {
        return super.equals(obj);
      }
      com.feeyo.raft.proto.Btreepb.Element other = (com.feeyo.raft.proto.Btreepb.Element) obj;

      boolean result = true;
      result = result && getKey()
          .equals(other.getKey());
      result = result && getValue()
          .equals(other.getValue());
      result = result && getCategory()
          .equals(other.getCategory());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + KEY_FIELD_NUMBER;
      hash = (53 * hash) + getKey().hashCode();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
      hash = (37 * hash) + CATEGORY_FIELD_NUMBER;
      hash = (53 * hash) + getCategory().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.feeyo.raft.proto.Btreepb.Element parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.feeyo.raft.proto.Btreepb.Element parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.feeyo.raft.proto.Btreepb.Element parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.feeyo.raft.proto.Btreepb.Element parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.feeyo.raft.proto.Btreepb.Element parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.feeyo.raft.proto.Btreepb.Element parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.feeyo.raft.proto.Btreepb.Element parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.feeyo.raft.proto.Btreepb.Element parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.feeyo.raft.proto.Btreepb.Element parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.feeyo.raft.proto.Btreepb.Element parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.feeyo.raft.proto.Btreepb.Element parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.feeyo.raft.proto.Btreepb.Element parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.feeyo.raft.proto.Btreepb.Element prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code raft.Element}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:raft.Element)
        com.feeyo.raft.proto.Btreepb.ElementOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.feeyo.raft.proto.Btreepb.internal_static_raft_Element_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.feeyo.raft.proto.Btreepb.internal_static_raft_Element_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.feeyo.raft.proto.Btreepb.Element.class, com.feeyo.raft.proto.Btreepb.Element.Builder.class);
      }

      // Construct using com.feeyo.raft.proto.Btreepb.Element.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        key_ = "";

        value_ = com.google.protobuf.ByteString.EMPTY;

        category_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.feeyo.raft.proto.Btreepb.internal_static_raft_Element_descriptor;
      }

      public com.feeyo.raft.proto.Btreepb.Element getDefaultInstanceForType() {
        return com.feeyo.raft.proto.Btreepb.Element.getDefaultInstance();
      }

      public com.feeyo.raft.proto.Btreepb.Element build() {
        com.feeyo.raft.proto.Btreepb.Element result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.feeyo.raft.proto.Btreepb.Element buildPartial() {
        com.feeyo.raft.proto.Btreepb.Element result = new com.feeyo.raft.proto.Btreepb.Element(this);
        result.key_ = key_;
        result.value_ = value_;
        result.category_ = category_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.feeyo.raft.proto.Btreepb.Element) {
          return mergeFrom((com.feeyo.raft.proto.Btreepb.Element)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.feeyo.raft.proto.Btreepb.Element other) {
        if (other == com.feeyo.raft.proto.Btreepb.Element.getDefaultInstance()) return this;
        if (!other.getKey().isEmpty()) {
          key_ = other.key_;
          onChanged();
        }
        if (other.getValue() != com.google.protobuf.ByteString.EMPTY) {
          setValue(other.getValue());
        }
        if (!other.getCategory().isEmpty()) {
          category_ = other.category_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.feeyo.raft.proto.Btreepb.Element parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.feeyo.raft.proto.Btreepb.Element) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object key_ = "";
      /**
       * <code>string key = 1;</code>
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string key = 1;</code>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string key = 1;</code>
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string key = 1;</code>
       */
      public Builder clearKey() {
        
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <code>string key = 1;</code>
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        key_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes value = 2;</code>
       */
      public com.google.protobuf.ByteString getValue() {
        return value_;
      }
      /**
       * <code>bytes value = 2;</code>
       */
      public Builder setValue(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes value = 2;</code>
       */
      public Builder clearValue() {
        
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }

      private java.lang.Object category_ = "";
      /**
       * <code>string category = 3;</code>
       */
      public java.lang.String getCategory() {
        java.lang.Object ref = category_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          category_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string category = 3;</code>
       */
      public com.google.protobuf.ByteString
          getCategoryBytes() {
        java.lang.Object ref = category_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          category_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string category = 3;</code>
       */
      public Builder setCategory(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        category_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string category = 3;</code>
       */
      public Builder clearCategory() {
        
        category_ = getDefaultInstance().getCategory();
        onChanged();
        return this;
      }
      /**
       * <code>string category = 3;</code>
       */
      public Builder setCategoryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        category_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:raft.Element)
    }

    // @@protoc_insertion_point(class_scope:raft.Element)
    private static final com.feeyo.raft.proto.Btreepb.Element DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.feeyo.raft.proto.Btreepb.Element();
    }

    public static com.feeyo.raft.proto.Btreepb.Element getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Element>
        PARSER = new com.google.protobuf.AbstractParser<Element>() {
      public Element parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Element(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Element> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Element> getParserForType() {
      return PARSER;
    }

    public com.feeyo.raft.proto.Btreepb.Element getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ElementCmdOrBuilder extends
      // @@protoc_insertion_point(interface_extends:raft.ElementCmd)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.raft.Operation op = 1;</code>
     */
    int getOpValue();
    /**
     * <code>.raft.Operation op = 1;</code>
     */
    com.feeyo.raft.proto.Btreepb.Operation getOp();

    /**
     * <code>repeated .raft.Element ele = 2;</code>
     */
    java.util.List<com.feeyo.raft.proto.Btreepb.Element> 
        getEleList();
    /**
     * <code>repeated .raft.Element ele = 2;</code>
     */
    com.feeyo.raft.proto.Btreepb.Element getEle(int index);
    /**
     * <code>repeated .raft.Element ele = 2;</code>
     */
    int getEleCount();
    /**
     * <code>repeated .raft.Element ele = 2;</code>
     */
    java.util.List<? extends com.feeyo.raft.proto.Btreepb.ElementOrBuilder> 
        getEleOrBuilderList();
    /**
     * <code>repeated .raft.Element ele = 2;</code>
     */
    com.feeyo.raft.proto.Btreepb.ElementOrBuilder getEleOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code raft.ElementCmd}
   */
  public  static final class ElementCmd extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:raft.ElementCmd)
      ElementCmdOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ElementCmd.newBuilder() to construct.
    private ElementCmd(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ElementCmd() {
      op_ = 0;
      ele_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ElementCmd(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              op_ = rawValue;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                ele_ = new java.util.ArrayList<com.feeyo.raft.proto.Btreepb.Element>();
                mutable_bitField0_ |= 0x00000002;
              }
              ele_.add(
                  input.readMessage(com.feeyo.raft.proto.Btreepb.Element.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          ele_ = java.util.Collections.unmodifiableList(ele_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.feeyo.raft.proto.Btreepb.internal_static_raft_ElementCmd_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.feeyo.raft.proto.Btreepb.internal_static_raft_ElementCmd_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.feeyo.raft.proto.Btreepb.ElementCmd.class, com.feeyo.raft.proto.Btreepb.ElementCmd.Builder.class);
    }

    private int bitField0_;
    public static final int OP_FIELD_NUMBER = 1;
    private int op_;
    /**
     * <code>.raft.Operation op = 1;</code>
     */
    public int getOpValue() {
      return op_;
    }
    /**
     * <code>.raft.Operation op = 1;</code>
     */
    public com.feeyo.raft.proto.Btreepb.Operation getOp() {
      com.feeyo.raft.proto.Btreepb.Operation result = com.feeyo.raft.proto.Btreepb.Operation.valueOf(op_);
      return result == null ? com.feeyo.raft.proto.Btreepb.Operation.UNRECOGNIZED : result;
    }

    public static final int ELE_FIELD_NUMBER = 2;
    private java.util.List<com.feeyo.raft.proto.Btreepb.Element> ele_;
    /**
     * <code>repeated .raft.Element ele = 2;</code>
     */
    public java.util.List<com.feeyo.raft.proto.Btreepb.Element> getEleList() {
      return ele_;
    }
    /**
     * <code>repeated .raft.Element ele = 2;</code>
     */
    public java.util.List<? extends com.feeyo.raft.proto.Btreepb.ElementOrBuilder> 
        getEleOrBuilderList() {
      return ele_;
    }
    /**
     * <code>repeated .raft.Element ele = 2;</code>
     */
    public int getEleCount() {
      return ele_.size();
    }
    /**
     * <code>repeated .raft.Element ele = 2;</code>
     */
    public com.feeyo.raft.proto.Btreepb.Element getEle(int index) {
      return ele_.get(index);
    }
    /**
     * <code>repeated .raft.Element ele = 2;</code>
     */
    public com.feeyo.raft.proto.Btreepb.ElementOrBuilder getEleOrBuilder(
        int index) {
      return ele_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (op_ != com.feeyo.raft.proto.Btreepb.Operation.Insert.getNumber()) {
        output.writeEnum(1, op_);
      }
      for (int i = 0; i < ele_.size(); i++) {
        output.writeMessage(2, ele_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (op_ != com.feeyo.raft.proto.Btreepb.Operation.Insert.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, op_);
      }
      for (int i = 0; i < ele_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, ele_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.feeyo.raft.proto.Btreepb.ElementCmd)) {
        return super.equals(obj);
      }
      com.feeyo.raft.proto.Btreepb.ElementCmd other = (com.feeyo.raft.proto.Btreepb.ElementCmd) obj;

      boolean result = true;
      result = result && op_ == other.op_;
      result = result && getEleList()
          .equals(other.getEleList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + OP_FIELD_NUMBER;
      hash = (53 * hash) + op_;
      if (getEleCount() > 0) {
        hash = (37 * hash) + ELE_FIELD_NUMBER;
        hash = (53 * hash) + getEleList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.feeyo.raft.proto.Btreepb.ElementCmd parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.feeyo.raft.proto.Btreepb.ElementCmd parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.feeyo.raft.proto.Btreepb.ElementCmd parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.feeyo.raft.proto.Btreepb.ElementCmd parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.feeyo.raft.proto.Btreepb.ElementCmd parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.feeyo.raft.proto.Btreepb.ElementCmd parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.feeyo.raft.proto.Btreepb.ElementCmd parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.feeyo.raft.proto.Btreepb.ElementCmd parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.feeyo.raft.proto.Btreepb.ElementCmd parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.feeyo.raft.proto.Btreepb.ElementCmd parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.feeyo.raft.proto.Btreepb.ElementCmd parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.feeyo.raft.proto.Btreepb.ElementCmd parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.feeyo.raft.proto.Btreepb.ElementCmd prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code raft.ElementCmd}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:raft.ElementCmd)
        com.feeyo.raft.proto.Btreepb.ElementCmdOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.feeyo.raft.proto.Btreepb.internal_static_raft_ElementCmd_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.feeyo.raft.proto.Btreepb.internal_static_raft_ElementCmd_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.feeyo.raft.proto.Btreepb.ElementCmd.class, com.feeyo.raft.proto.Btreepb.ElementCmd.Builder.class);
      }

      // Construct using com.feeyo.raft.proto.Btreepb.ElementCmd.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getEleFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        op_ = 0;

        if (eleBuilder_ == null) {
          ele_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          eleBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.feeyo.raft.proto.Btreepb.internal_static_raft_ElementCmd_descriptor;
      }

      public com.feeyo.raft.proto.Btreepb.ElementCmd getDefaultInstanceForType() {
        return com.feeyo.raft.proto.Btreepb.ElementCmd.getDefaultInstance();
      }

      public com.feeyo.raft.proto.Btreepb.ElementCmd build() {
        com.feeyo.raft.proto.Btreepb.ElementCmd result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.feeyo.raft.proto.Btreepb.ElementCmd buildPartial() {
        com.feeyo.raft.proto.Btreepb.ElementCmd result = new com.feeyo.raft.proto.Btreepb.ElementCmd(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.op_ = op_;
        if (eleBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            ele_ = java.util.Collections.unmodifiableList(ele_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.ele_ = ele_;
        } else {
          result.ele_ = eleBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.feeyo.raft.proto.Btreepb.ElementCmd) {
          return mergeFrom((com.feeyo.raft.proto.Btreepb.ElementCmd)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.feeyo.raft.proto.Btreepb.ElementCmd other) {
        if (other == com.feeyo.raft.proto.Btreepb.ElementCmd.getDefaultInstance()) return this;
        if (other.op_ != 0) {
          setOpValue(other.getOpValue());
        }
        if (eleBuilder_ == null) {
          if (!other.ele_.isEmpty()) {
            if (ele_.isEmpty()) {
              ele_ = other.ele_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureEleIsMutable();
              ele_.addAll(other.ele_);
            }
            onChanged();
          }
        } else {
          if (!other.ele_.isEmpty()) {
            if (eleBuilder_.isEmpty()) {
              eleBuilder_.dispose();
              eleBuilder_ = null;
              ele_ = other.ele_;
              bitField0_ = (bitField0_ & ~0x00000002);
              eleBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getEleFieldBuilder() : null;
            } else {
              eleBuilder_.addAllMessages(other.ele_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.feeyo.raft.proto.Btreepb.ElementCmd parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.feeyo.raft.proto.Btreepb.ElementCmd) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int op_ = 0;
      /**
       * <code>.raft.Operation op = 1;</code>
       */
      public int getOpValue() {
        return op_;
      }
      /**
       * <code>.raft.Operation op = 1;</code>
       */
      public Builder setOpValue(int value) {
        op_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.raft.Operation op = 1;</code>
       */
      public com.feeyo.raft.proto.Btreepb.Operation getOp() {
        com.feeyo.raft.proto.Btreepb.Operation result = com.feeyo.raft.proto.Btreepb.Operation.valueOf(op_);
        return result == null ? com.feeyo.raft.proto.Btreepb.Operation.UNRECOGNIZED : result;
      }
      /**
       * <code>.raft.Operation op = 1;</code>
       */
      public Builder setOp(com.feeyo.raft.proto.Btreepb.Operation value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        op_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.raft.Operation op = 1;</code>
       */
      public Builder clearOp() {
        
        op_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.feeyo.raft.proto.Btreepb.Element> ele_ =
        java.util.Collections.emptyList();
      private void ensureEleIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          ele_ = new java.util.ArrayList<com.feeyo.raft.proto.Btreepb.Element>(ele_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.feeyo.raft.proto.Btreepb.Element, com.feeyo.raft.proto.Btreepb.Element.Builder, com.feeyo.raft.proto.Btreepb.ElementOrBuilder> eleBuilder_;

      /**
       * <code>repeated .raft.Element ele = 2;</code>
       */
      public java.util.List<com.feeyo.raft.proto.Btreepb.Element> getEleList() {
        if (eleBuilder_ == null) {
          return java.util.Collections.unmodifiableList(ele_);
        } else {
          return eleBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .raft.Element ele = 2;</code>
       */
      public int getEleCount() {
        if (eleBuilder_ == null) {
          return ele_.size();
        } else {
          return eleBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .raft.Element ele = 2;</code>
       */
      public com.feeyo.raft.proto.Btreepb.Element getEle(int index) {
        if (eleBuilder_ == null) {
          return ele_.get(index);
        } else {
          return eleBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .raft.Element ele = 2;</code>
       */
      public Builder setEle(
          int index, com.feeyo.raft.proto.Btreepb.Element value) {
        if (eleBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEleIsMutable();
          ele_.set(index, value);
          onChanged();
        } else {
          eleBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .raft.Element ele = 2;</code>
       */
      public Builder setEle(
          int index, com.feeyo.raft.proto.Btreepb.Element.Builder builderForValue) {
        if (eleBuilder_ == null) {
          ensureEleIsMutable();
          ele_.set(index, builderForValue.build());
          onChanged();
        } else {
          eleBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .raft.Element ele = 2;</code>
       */
      public Builder addEle(com.feeyo.raft.proto.Btreepb.Element value) {
        if (eleBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEleIsMutable();
          ele_.add(value);
          onChanged();
        } else {
          eleBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .raft.Element ele = 2;</code>
       */
      public Builder addEle(
          int index, com.feeyo.raft.proto.Btreepb.Element value) {
        if (eleBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEleIsMutable();
          ele_.add(index, value);
          onChanged();
        } else {
          eleBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .raft.Element ele = 2;</code>
       */
      public Builder addEle(
          com.feeyo.raft.proto.Btreepb.Element.Builder builderForValue) {
        if (eleBuilder_ == null) {
          ensureEleIsMutable();
          ele_.add(builderForValue.build());
          onChanged();
        } else {
          eleBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .raft.Element ele = 2;</code>
       */
      public Builder addEle(
          int index, com.feeyo.raft.proto.Btreepb.Element.Builder builderForValue) {
        if (eleBuilder_ == null) {
          ensureEleIsMutable();
          ele_.add(index, builderForValue.build());
          onChanged();
        } else {
          eleBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .raft.Element ele = 2;</code>
       */
      public Builder addAllEle(
          java.lang.Iterable<? extends com.feeyo.raft.proto.Btreepb.Element> values) {
        if (eleBuilder_ == null) {
          ensureEleIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, ele_);
          onChanged();
        } else {
          eleBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .raft.Element ele = 2;</code>
       */
      public Builder clearEle() {
        if (eleBuilder_ == null) {
          ele_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          eleBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .raft.Element ele = 2;</code>
       */
      public Builder removeEle(int index) {
        if (eleBuilder_ == null) {
          ensureEleIsMutable();
          ele_.remove(index);
          onChanged();
        } else {
          eleBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .raft.Element ele = 2;</code>
       */
      public com.feeyo.raft.proto.Btreepb.Element.Builder getEleBuilder(
          int index) {
        return getEleFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .raft.Element ele = 2;</code>
       */
      public com.feeyo.raft.proto.Btreepb.ElementOrBuilder getEleOrBuilder(
          int index) {
        if (eleBuilder_ == null) {
          return ele_.get(index);  } else {
          return eleBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .raft.Element ele = 2;</code>
       */
      public java.util.List<? extends com.feeyo.raft.proto.Btreepb.ElementOrBuilder> 
           getEleOrBuilderList() {
        if (eleBuilder_ != null) {
          return eleBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(ele_);
        }
      }
      /**
       * <code>repeated .raft.Element ele = 2;</code>
       */
      public com.feeyo.raft.proto.Btreepb.Element.Builder addEleBuilder() {
        return getEleFieldBuilder().addBuilder(
            com.feeyo.raft.proto.Btreepb.Element.getDefaultInstance());
      }
      /**
       * <code>repeated .raft.Element ele = 2;</code>
       */
      public com.feeyo.raft.proto.Btreepb.Element.Builder addEleBuilder(
          int index) {
        return getEleFieldBuilder().addBuilder(
            index, com.feeyo.raft.proto.Btreepb.Element.getDefaultInstance());
      }
      /**
       * <code>repeated .raft.Element ele = 2;</code>
       */
      public java.util.List<com.feeyo.raft.proto.Btreepb.Element.Builder> 
           getEleBuilderList() {
        return getEleFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.feeyo.raft.proto.Btreepb.Element, com.feeyo.raft.proto.Btreepb.Element.Builder, com.feeyo.raft.proto.Btreepb.ElementOrBuilder> 
          getEleFieldBuilder() {
        if (eleBuilder_ == null) {
          eleBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.feeyo.raft.proto.Btreepb.Element, com.feeyo.raft.proto.Btreepb.Element.Builder, com.feeyo.raft.proto.Btreepb.ElementOrBuilder>(
                  ele_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          ele_ = null;
        }
        return eleBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:raft.ElementCmd)
    }

    // @@protoc_insertion_point(class_scope:raft.ElementCmd)
    private static final com.feeyo.raft.proto.Btreepb.ElementCmd DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.feeyo.raft.proto.Btreepb.ElementCmd();
    }

    public static com.feeyo.raft.proto.Btreepb.ElementCmd getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ElementCmd>
        PARSER = new com.google.protobuf.AbstractParser<ElementCmd>() {
      public ElementCmd parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ElementCmd(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ElementCmd> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ElementCmd> getParserForType() {
      return PARSER;
    }

    public com.feeyo.raft.proto.Btreepb.ElementCmd getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_raft_Element_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_raft_Element_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_raft_ElementCmd_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_raft_ElementCmd_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rbtreepb.proto\022\004raft\032\014raftpb.proto\"7\n\007E" +
      "lement\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\014\022\020\n\010ca" +
      "tegory\030\003 \001(\t\"E\n\nElementCmd\022\033\n\002op\030\001 \001(\0162\017" +
      ".raft.Operation\022\032\n\003ele\030\002 \003(\0132\r.raft.Elem" +
      "ent*#\n\tOperation\022\n\n\006Insert\020\000\022\n\n\006Delete\020\001" +
      "B!\n\024com.feeyo.raft.protoB\007BtreepbH\001P\000b\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.feeyo.raft.proto.Raftpb.getDescriptor(),
        }, assigner);
    internal_static_raft_Element_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_raft_Element_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_raft_Element_descriptor,
        new java.lang.String[] { "Key", "Value", "Category", });
    internal_static_raft_ElementCmd_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_raft_ElementCmd_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_raft_ElementCmd_descriptor,
        new java.lang.String[] { "Op", "Ele", });
    com.feeyo.raft.proto.Raftpb.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
