// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: newdbpb.proto

package com.feeyo.raft.proto;

public final class Newdbpb {
  private Newdbpb() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code raft.Operation}
   */
  public enum Operation
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Insert = 0;</code>
     */
    Insert(0),
    /**
     * <code>Delete = 1;</code>
     */
    Delete(1),
    /**
     * <code>DDL = 2;</code>
     */
    DDL(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>Insert = 0;</code>
     */
    public static final int Insert_VALUE = 0;
    /**
     * <code>Delete = 1;</code>
     */
    public static final int Delete_VALUE = 1;
    /**
     * <code>DDL = 2;</code>
     */
    public static final int DDL_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Operation valueOf(int value) {
      return forNumber(value);
    }

    public static Operation forNumber(int value) {
      switch (value) {
        case 0: return Insert;
        case 1: return Delete;
        case 2: return DDL;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Operation>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Operation> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Operation>() {
            public Operation findValueByNumber(int number) {
              return Operation.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.feeyo.raft.proto.Newdbpb.getDescriptor().getEnumTypes().get(0);
    }

    private static final Operation[] VALUES = values();

    public static Operation valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Operation(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:raft.Operation)
  }

  /**
   * Protobuf enum {@code raft.ColumnFamilyHandle}
   */
  public enum ColumnFamilyHandle
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>DefaultCfh = 0;</code>
     */
    DefaultCfh(0),
    /**
     * <code>WriteCfh = 1;</code>
     */
    WriteCfh(1),
    /**
     * <code>LockCfh = 2;</code>
     */
    LockCfh(2),
    /**
     * <code>RawCfh = 3;</code>
     */
    RawCfh(3),
    /**
     * <pre>
     * key/value
     * </pre>
     *
     * <code>RawKvCfh = 4;</code>
     */
    RawKvCfh(4),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>DefaultCfh = 0;</code>
     */
    public static final int DefaultCfh_VALUE = 0;
    /**
     * <code>WriteCfh = 1;</code>
     */
    public static final int WriteCfh_VALUE = 1;
    /**
     * <code>LockCfh = 2;</code>
     */
    public static final int LockCfh_VALUE = 2;
    /**
     * <code>RawCfh = 3;</code>
     */
    public static final int RawCfh_VALUE = 3;
    /**
     * <pre>
     * key/value
     * </pre>
     *
     * <code>RawKvCfh = 4;</code>
     */
    public static final int RawKvCfh_VALUE = 4;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ColumnFamilyHandle valueOf(int value) {
      return forNumber(value);
    }

    public static ColumnFamilyHandle forNumber(int value) {
      switch (value) {
        case 0: return DefaultCfh;
        case 1: return WriteCfh;
        case 2: return LockCfh;
        case 3: return RawCfh;
        case 4: return RawKvCfh;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ColumnFamilyHandle>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ColumnFamilyHandle> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ColumnFamilyHandle>() {
            public ColumnFamilyHandle findValueByNumber(int number) {
              return ColumnFamilyHandle.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.feeyo.raft.proto.Newdbpb.getDescriptor().getEnumTypes().get(1);
    }

    private static final ColumnFamilyHandle[] VALUES = values();

    public static ColumnFamilyHandle valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ColumnFamilyHandle(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:raft.ColumnFamilyHandle)
  }

  public interface ProposeCmdOrBuilder extends
      // @@protoc_insertion_point(interface_extends:raft.ProposeCmd)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.raft.Operation op = 1;</code>
     */
    int getOpValue();
    /**
     * <code>.raft.Operation op = 1;</code>
     */
    com.feeyo.raft.proto.Newdbpb.Operation getOp();

    /**
     * <code>.raft.ColumnFamilyHandle cfh = 2;</code>
     */
    int getCfhValue();
    /**
     * <code>.raft.ColumnFamilyHandle cfh = 2;</code>
     */
    com.feeyo.raft.proto.Newdbpb.ColumnFamilyHandle getCfh();

    /**
     * <code>repeated .raft.KeyValue kv = 3;</code>
     */
    java.util.List<com.feeyo.raft.proto.Raftpb.KeyValue> 
        getKvList();
    /**
     * <code>repeated .raft.KeyValue kv = 3;</code>
     */
    com.feeyo.raft.proto.Raftpb.KeyValue getKv(int index);
    /**
     * <code>repeated .raft.KeyValue kv = 3;</code>
     */
    int getKvCount();
    /**
     * <code>repeated .raft.KeyValue kv = 3;</code>
     */
    java.util.List<? extends com.feeyo.raft.proto.Raftpb.KeyValueOrBuilder> 
        getKvOrBuilderList();
    /**
     * <code>repeated .raft.KeyValue kv = 3;</code>
     */
    com.feeyo.raft.proto.Raftpb.KeyValueOrBuilder getKvOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code raft.ProposeCmd}
   */
  public  static final class ProposeCmd extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:raft.ProposeCmd)
      ProposeCmdOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ProposeCmd.newBuilder() to construct.
    private ProposeCmd(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProposeCmd() {
      op_ = 0;
      cfh_ = 0;
      kv_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ProposeCmd(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              op_ = rawValue;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              cfh_ = rawValue;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                kv_ = new java.util.ArrayList<com.feeyo.raft.proto.Raftpb.KeyValue>();
                mutable_bitField0_ |= 0x00000004;
              }
              kv_.add(
                  input.readMessage(com.feeyo.raft.proto.Raftpb.KeyValue.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          kv_ = java.util.Collections.unmodifiableList(kv_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.feeyo.raft.proto.Newdbpb.internal_static_raft_ProposeCmd_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.feeyo.raft.proto.Newdbpb.internal_static_raft_ProposeCmd_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.feeyo.raft.proto.Newdbpb.ProposeCmd.class, com.feeyo.raft.proto.Newdbpb.ProposeCmd.Builder.class);
    }

    private int bitField0_;
    public static final int OP_FIELD_NUMBER = 1;
    private int op_;
    /**
     * <code>.raft.Operation op = 1;</code>
     */
    public int getOpValue() {
      return op_;
    }
    /**
     * <code>.raft.Operation op = 1;</code>
     */
    public com.feeyo.raft.proto.Newdbpb.Operation getOp() {
      com.feeyo.raft.proto.Newdbpb.Operation result = com.feeyo.raft.proto.Newdbpb.Operation.valueOf(op_);
      return result == null ? com.feeyo.raft.proto.Newdbpb.Operation.UNRECOGNIZED : result;
    }

    public static final int CFH_FIELD_NUMBER = 2;
    private int cfh_;
    /**
     * <code>.raft.ColumnFamilyHandle cfh = 2;</code>
     */
    public int getCfhValue() {
      return cfh_;
    }
    /**
     * <code>.raft.ColumnFamilyHandle cfh = 2;</code>
     */
    public com.feeyo.raft.proto.Newdbpb.ColumnFamilyHandle getCfh() {
      com.feeyo.raft.proto.Newdbpb.ColumnFamilyHandle result = com.feeyo.raft.proto.Newdbpb.ColumnFamilyHandle.valueOf(cfh_);
      return result == null ? com.feeyo.raft.proto.Newdbpb.ColumnFamilyHandle.UNRECOGNIZED : result;
    }

    public static final int KV_FIELD_NUMBER = 3;
    private java.util.List<com.feeyo.raft.proto.Raftpb.KeyValue> kv_;
    /**
     * <code>repeated .raft.KeyValue kv = 3;</code>
     */
    public java.util.List<com.feeyo.raft.proto.Raftpb.KeyValue> getKvList() {
      return kv_;
    }
    /**
     * <code>repeated .raft.KeyValue kv = 3;</code>
     */
    public java.util.List<? extends com.feeyo.raft.proto.Raftpb.KeyValueOrBuilder> 
        getKvOrBuilderList() {
      return kv_;
    }
    /**
     * <code>repeated .raft.KeyValue kv = 3;</code>
     */
    public int getKvCount() {
      return kv_.size();
    }
    /**
     * <code>repeated .raft.KeyValue kv = 3;</code>
     */
    public com.feeyo.raft.proto.Raftpb.KeyValue getKv(int index) {
      return kv_.get(index);
    }
    /**
     * <code>repeated .raft.KeyValue kv = 3;</code>
     */
    public com.feeyo.raft.proto.Raftpb.KeyValueOrBuilder getKvOrBuilder(
        int index) {
      return kv_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (op_ != com.feeyo.raft.proto.Newdbpb.Operation.Insert.getNumber()) {
        output.writeEnum(1, op_);
      }
      if (cfh_ != com.feeyo.raft.proto.Newdbpb.ColumnFamilyHandle.DefaultCfh.getNumber()) {
        output.writeEnum(2, cfh_);
      }
      for (int i = 0; i < kv_.size(); i++) {
        output.writeMessage(3, kv_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (op_ != com.feeyo.raft.proto.Newdbpb.Operation.Insert.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, op_);
      }
      if (cfh_ != com.feeyo.raft.proto.Newdbpb.ColumnFamilyHandle.DefaultCfh.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, cfh_);
      }
      for (int i = 0; i < kv_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, kv_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.feeyo.raft.proto.Newdbpb.ProposeCmd)) {
        return super.equals(obj);
      }
      com.feeyo.raft.proto.Newdbpb.ProposeCmd other = (com.feeyo.raft.proto.Newdbpb.ProposeCmd) obj;

      boolean result = true;
      result = result && op_ == other.op_;
      result = result && cfh_ == other.cfh_;
      result = result && getKvList()
          .equals(other.getKvList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + OP_FIELD_NUMBER;
      hash = (53 * hash) + op_;
      hash = (37 * hash) + CFH_FIELD_NUMBER;
      hash = (53 * hash) + cfh_;
      if (getKvCount() > 0) {
        hash = (37 * hash) + KV_FIELD_NUMBER;
        hash = (53 * hash) + getKvList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.feeyo.raft.proto.Newdbpb.ProposeCmd parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.feeyo.raft.proto.Newdbpb.ProposeCmd parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.feeyo.raft.proto.Newdbpb.ProposeCmd parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.feeyo.raft.proto.Newdbpb.ProposeCmd parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.feeyo.raft.proto.Newdbpb.ProposeCmd parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.feeyo.raft.proto.Newdbpb.ProposeCmd parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.feeyo.raft.proto.Newdbpb.ProposeCmd parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.feeyo.raft.proto.Newdbpb.ProposeCmd parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.feeyo.raft.proto.Newdbpb.ProposeCmd parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.feeyo.raft.proto.Newdbpb.ProposeCmd parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.feeyo.raft.proto.Newdbpb.ProposeCmd parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.feeyo.raft.proto.Newdbpb.ProposeCmd parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.feeyo.raft.proto.Newdbpb.ProposeCmd prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code raft.ProposeCmd}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:raft.ProposeCmd)
        com.feeyo.raft.proto.Newdbpb.ProposeCmdOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.feeyo.raft.proto.Newdbpb.internal_static_raft_ProposeCmd_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.feeyo.raft.proto.Newdbpb.internal_static_raft_ProposeCmd_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.feeyo.raft.proto.Newdbpb.ProposeCmd.class, com.feeyo.raft.proto.Newdbpb.ProposeCmd.Builder.class);
      }

      // Construct using com.feeyo.raft.proto.Newdbpb.ProposeCmd.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getKvFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        op_ = 0;

        cfh_ = 0;

        if (kvBuilder_ == null) {
          kv_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          kvBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.feeyo.raft.proto.Newdbpb.internal_static_raft_ProposeCmd_descriptor;
      }

      public com.feeyo.raft.proto.Newdbpb.ProposeCmd getDefaultInstanceForType() {
        return com.feeyo.raft.proto.Newdbpb.ProposeCmd.getDefaultInstance();
      }

      public com.feeyo.raft.proto.Newdbpb.ProposeCmd build() {
        com.feeyo.raft.proto.Newdbpb.ProposeCmd result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.feeyo.raft.proto.Newdbpb.ProposeCmd buildPartial() {
        com.feeyo.raft.proto.Newdbpb.ProposeCmd result = new com.feeyo.raft.proto.Newdbpb.ProposeCmd(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.op_ = op_;
        result.cfh_ = cfh_;
        if (kvBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            kv_ = java.util.Collections.unmodifiableList(kv_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.kv_ = kv_;
        } else {
          result.kv_ = kvBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.feeyo.raft.proto.Newdbpb.ProposeCmd) {
          return mergeFrom((com.feeyo.raft.proto.Newdbpb.ProposeCmd)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.feeyo.raft.proto.Newdbpb.ProposeCmd other) {
        if (other == com.feeyo.raft.proto.Newdbpb.ProposeCmd.getDefaultInstance()) return this;
        if (other.op_ != 0) {
          setOpValue(other.getOpValue());
        }
        if (other.cfh_ != 0) {
          setCfhValue(other.getCfhValue());
        }
        if (kvBuilder_ == null) {
          if (!other.kv_.isEmpty()) {
            if (kv_.isEmpty()) {
              kv_ = other.kv_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureKvIsMutable();
              kv_.addAll(other.kv_);
            }
            onChanged();
          }
        } else {
          if (!other.kv_.isEmpty()) {
            if (kvBuilder_.isEmpty()) {
              kvBuilder_.dispose();
              kvBuilder_ = null;
              kv_ = other.kv_;
              bitField0_ = (bitField0_ & ~0x00000004);
              kvBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getKvFieldBuilder() : null;
            } else {
              kvBuilder_.addAllMessages(other.kv_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.feeyo.raft.proto.Newdbpb.ProposeCmd parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.feeyo.raft.proto.Newdbpb.ProposeCmd) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int op_ = 0;
      /**
       * <code>.raft.Operation op = 1;</code>
       */
      public int getOpValue() {
        return op_;
      }
      /**
       * <code>.raft.Operation op = 1;</code>
       */
      public Builder setOpValue(int value) {
        op_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.raft.Operation op = 1;</code>
       */
      public com.feeyo.raft.proto.Newdbpb.Operation getOp() {
        com.feeyo.raft.proto.Newdbpb.Operation result = com.feeyo.raft.proto.Newdbpb.Operation.valueOf(op_);
        return result == null ? com.feeyo.raft.proto.Newdbpb.Operation.UNRECOGNIZED : result;
      }
      /**
       * <code>.raft.Operation op = 1;</code>
       */
      public Builder setOp(com.feeyo.raft.proto.Newdbpb.Operation value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        op_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.raft.Operation op = 1;</code>
       */
      public Builder clearOp() {
        
        op_ = 0;
        onChanged();
        return this;
      }

      private int cfh_ = 0;
      /**
       * <code>.raft.ColumnFamilyHandle cfh = 2;</code>
       */
      public int getCfhValue() {
        return cfh_;
      }
      /**
       * <code>.raft.ColumnFamilyHandle cfh = 2;</code>
       */
      public Builder setCfhValue(int value) {
        cfh_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.raft.ColumnFamilyHandle cfh = 2;</code>
       */
      public com.feeyo.raft.proto.Newdbpb.ColumnFamilyHandle getCfh() {
        com.feeyo.raft.proto.Newdbpb.ColumnFamilyHandle result = com.feeyo.raft.proto.Newdbpb.ColumnFamilyHandle.valueOf(cfh_);
        return result == null ? com.feeyo.raft.proto.Newdbpb.ColumnFamilyHandle.UNRECOGNIZED : result;
      }
      /**
       * <code>.raft.ColumnFamilyHandle cfh = 2;</code>
       */
      public Builder setCfh(com.feeyo.raft.proto.Newdbpb.ColumnFamilyHandle value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        cfh_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.raft.ColumnFamilyHandle cfh = 2;</code>
       */
      public Builder clearCfh() {
        
        cfh_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.feeyo.raft.proto.Raftpb.KeyValue> kv_ =
        java.util.Collections.emptyList();
      private void ensureKvIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          kv_ = new java.util.ArrayList<com.feeyo.raft.proto.Raftpb.KeyValue>(kv_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.feeyo.raft.proto.Raftpb.KeyValue, com.feeyo.raft.proto.Raftpb.KeyValue.Builder, com.feeyo.raft.proto.Raftpb.KeyValueOrBuilder> kvBuilder_;

      /**
       * <code>repeated .raft.KeyValue kv = 3;</code>
       */
      public java.util.List<com.feeyo.raft.proto.Raftpb.KeyValue> getKvList() {
        if (kvBuilder_ == null) {
          return java.util.Collections.unmodifiableList(kv_);
        } else {
          return kvBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .raft.KeyValue kv = 3;</code>
       */
      public int getKvCount() {
        if (kvBuilder_ == null) {
          return kv_.size();
        } else {
          return kvBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .raft.KeyValue kv = 3;</code>
       */
      public com.feeyo.raft.proto.Raftpb.KeyValue getKv(int index) {
        if (kvBuilder_ == null) {
          return kv_.get(index);
        } else {
          return kvBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .raft.KeyValue kv = 3;</code>
       */
      public Builder setKv(
          int index, com.feeyo.raft.proto.Raftpb.KeyValue value) {
        if (kvBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureKvIsMutable();
          kv_.set(index, value);
          onChanged();
        } else {
          kvBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .raft.KeyValue kv = 3;</code>
       */
      public Builder setKv(
          int index, com.feeyo.raft.proto.Raftpb.KeyValue.Builder builderForValue) {
        if (kvBuilder_ == null) {
          ensureKvIsMutable();
          kv_.set(index, builderForValue.build());
          onChanged();
        } else {
          kvBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .raft.KeyValue kv = 3;</code>
       */
      public Builder addKv(com.feeyo.raft.proto.Raftpb.KeyValue value) {
        if (kvBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureKvIsMutable();
          kv_.add(value);
          onChanged();
        } else {
          kvBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .raft.KeyValue kv = 3;</code>
       */
      public Builder addKv(
          int index, com.feeyo.raft.proto.Raftpb.KeyValue value) {
        if (kvBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureKvIsMutable();
          kv_.add(index, value);
          onChanged();
        } else {
          kvBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .raft.KeyValue kv = 3;</code>
       */
      public Builder addKv(
          com.feeyo.raft.proto.Raftpb.KeyValue.Builder builderForValue) {
        if (kvBuilder_ == null) {
          ensureKvIsMutable();
          kv_.add(builderForValue.build());
          onChanged();
        } else {
          kvBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .raft.KeyValue kv = 3;</code>
       */
      public Builder addKv(
          int index, com.feeyo.raft.proto.Raftpb.KeyValue.Builder builderForValue) {
        if (kvBuilder_ == null) {
          ensureKvIsMutable();
          kv_.add(index, builderForValue.build());
          onChanged();
        } else {
          kvBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .raft.KeyValue kv = 3;</code>
       */
      public Builder addAllKv(
          java.lang.Iterable<? extends com.feeyo.raft.proto.Raftpb.KeyValue> values) {
        if (kvBuilder_ == null) {
          ensureKvIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, kv_);
          onChanged();
        } else {
          kvBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .raft.KeyValue kv = 3;</code>
       */
      public Builder clearKv() {
        if (kvBuilder_ == null) {
          kv_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          kvBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .raft.KeyValue kv = 3;</code>
       */
      public Builder removeKv(int index) {
        if (kvBuilder_ == null) {
          ensureKvIsMutable();
          kv_.remove(index);
          onChanged();
        } else {
          kvBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .raft.KeyValue kv = 3;</code>
       */
      public com.feeyo.raft.proto.Raftpb.KeyValue.Builder getKvBuilder(
          int index) {
        return getKvFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .raft.KeyValue kv = 3;</code>
       */
      public com.feeyo.raft.proto.Raftpb.KeyValueOrBuilder getKvOrBuilder(
          int index) {
        if (kvBuilder_ == null) {
          return kv_.get(index);  } else {
          return kvBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .raft.KeyValue kv = 3;</code>
       */
      public java.util.List<? extends com.feeyo.raft.proto.Raftpb.KeyValueOrBuilder> 
           getKvOrBuilderList() {
        if (kvBuilder_ != null) {
          return kvBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(kv_);
        }
      }
      /**
       * <code>repeated .raft.KeyValue kv = 3;</code>
       */
      public com.feeyo.raft.proto.Raftpb.KeyValue.Builder addKvBuilder() {
        return getKvFieldBuilder().addBuilder(
            com.feeyo.raft.proto.Raftpb.KeyValue.getDefaultInstance());
      }
      /**
       * <code>repeated .raft.KeyValue kv = 3;</code>
       */
      public com.feeyo.raft.proto.Raftpb.KeyValue.Builder addKvBuilder(
          int index) {
        return getKvFieldBuilder().addBuilder(
            index, com.feeyo.raft.proto.Raftpb.KeyValue.getDefaultInstance());
      }
      /**
       * <code>repeated .raft.KeyValue kv = 3;</code>
       */
      public java.util.List<com.feeyo.raft.proto.Raftpb.KeyValue.Builder> 
           getKvBuilderList() {
        return getKvFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.feeyo.raft.proto.Raftpb.KeyValue, com.feeyo.raft.proto.Raftpb.KeyValue.Builder, com.feeyo.raft.proto.Raftpb.KeyValueOrBuilder> 
          getKvFieldBuilder() {
        if (kvBuilder_ == null) {
          kvBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.feeyo.raft.proto.Raftpb.KeyValue, com.feeyo.raft.proto.Raftpb.KeyValue.Builder, com.feeyo.raft.proto.Raftpb.KeyValueOrBuilder>(
                  kv_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          kv_ = null;
        }
        return kvBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:raft.ProposeCmd)
    }

    // @@protoc_insertion_point(class_scope:raft.ProposeCmd)
    private static final com.feeyo.raft.proto.Newdbpb.ProposeCmd DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.feeyo.raft.proto.Newdbpb.ProposeCmd();
    }

    public static com.feeyo.raft.proto.Newdbpb.ProposeCmd getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProposeCmd>
        PARSER = new com.google.protobuf.AbstractParser<ProposeCmd>() {
      public ProposeCmd parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProposeCmd(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProposeCmd> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProposeCmd> getParserForType() {
      return PARSER;
    }

    public com.feeyo.raft.proto.Newdbpb.ProposeCmd getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_raft_ProposeCmd_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_raft_ProposeCmd_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rnewdbpb.proto\022\004raft\032\014raftpb.proto\"l\n\nP" +
      "roposeCmd\022\033\n\002op\030\001 \001(\0162\017.raft.Operation\022%" +
      "\n\003cfh\030\002 \001(\0162\030.raft.ColumnFamilyHandle\022\032\n" +
      "\002kv\030\003 \003(\0132\016.raft.KeyValue*,\n\tOperation\022\n" +
      "\n\006Insert\020\000\022\n\n\006Delete\020\001\022\007\n\003DDL\020\002*Y\n\022Colum" +
      "nFamilyHandle\022\016\n\nDefaultCfh\020\000\022\014\n\010WriteCf" +
      "h\020\001\022\013\n\007LockCfh\020\002\022\n\n\006RawCfh\020\003\022\014\n\010RawKvCfh" +
      "\020\004B!\n\024com.feeyo.raft.protoB\007NewdbpbH\001P\000b" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.feeyo.raft.proto.Raftpb.getDescriptor(),
        }, assigner);
    internal_static_raft_ProposeCmd_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_raft_ProposeCmd_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_raft_ProposeCmd_descriptor,
        new java.lang.String[] { "Op", "Cfh", "Kv", });
    com.feeyo.raft.proto.Raftpb.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
